#!/usr/bin/env bash
# bump-to-tag.sh <tag>
#
# Bumps the Hearth formula in Naoray/homebrew-tap to a given release tag.
# Downloads both arch tarballs from the GitHub Release, computes sha256, rewrites
# Formula/hearth.rb, commits to a branch, pushes, and opens a PR.
#
# Does NOT auto-merge. Maintainer approves.
#
# Usage:
#   bump-to-tag.sh v0.3.0
#
# Requires: gh, curl, shasum, sed, git

set -euo pipefail

TAG="${1:-}"
if [[ -z "$TAG" ]]; then
  echo "usage: $0 <tag>   e.g. $0 v0.3.0" >&2
  exit 1
fi

if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.]+)?$ ]]; then
  echo "tag must look like vX.Y.Z or vX.Y.Z-rc.N (got: $TAG)" >&2
  exit 1
fi

VERSION="${TAG#v}"
SOURCE_REPO="Naoray/hearth"
TAP_REPO="Naoray/homebrew-tap"
TAP_DIR="${TAP_DIR:-/tmp/hearth-tap}"
FORMULA="Formula/hearth.rb"
BRANCH="bump/hearth-${VERSION}"

ARM_ASSET="hearth-${TAG}-aarch64-apple-darwin.tar.gz"
X86_ASSET="hearth-${TAG}-x86_64-apple-darwin.tar.gz"
ARM_URL="https://github.com/${SOURCE_REPO}/releases/download/${TAG}/${ARM_ASSET}"
X86_URL="https://github.com/${SOURCE_REPO}/releases/download/${TAG}/${X86_ASSET}"

echo "==> Verifying release ${TAG} exists on ${SOURCE_REPO}"
if ! gh release view "$TAG" -R "$SOURCE_REPO" --json assets >/tmp/hearth-release.json 2>/dev/null; then
  echo "release ${TAG} not found on ${SOURCE_REPO}" >&2
  exit 1
fi

for asset in "$ARM_ASSET" "$X86_ASSET"; do
  if ! grep -q "\"$asset\"" /tmp/hearth-release.json; then
    echo "release ${TAG} missing asset: $asset" >&2
    exit 1
  fi
done

echo "==> Cloning tap repo ${TAP_REPO} -> ${TAP_DIR}"
if [[ -d "$TAP_DIR/.git" ]]; then
  git -C "$TAP_DIR" fetch origin
  git -C "$TAP_DIR" checkout main
  git -C "$TAP_DIR" reset --hard origin/main
else
  rm -rf "$TAP_DIR"
  gh repo clone "$TAP_REPO" "$TAP_DIR"
fi

cd "$TAP_DIR"

echo "==> Downloading + hashing arm64 asset"
ARM_SHA=$(curl -sL "$ARM_URL" | shasum -a 256 | awk '{print $1}')
echo "    arm64 sha256: $ARM_SHA"

echo "==> Downloading + hashing x86_64 asset"
X86_SHA=$(curl -sL "$X86_URL" | shasum -a 256 | awk '{print $1}')
echo "    x86_64 sha256: $X86_SHA"

if [[ ${#ARM_SHA} -ne 64 || ${#X86_SHA} -ne 64 ]]; then
  echo "sha256 computation failed (asset download may have returned an HTML error page)" >&2
  exit 1
fi

echo "==> Rewriting ${FORMULA}"
# Use perl in-place for portable, regex-anchored edits.
perl -i -pe "s|^(  version )\".*\"|\${1}\"$VERSION\"|" "$FORMULA"

perl -i -pe "s|releases/download/v[^/]+/hearth-v[^-]+(-[^-]+)?-aarch64-apple-darwin\.tar\.gz|releases/download/$TAG/hearth-$TAG-aarch64-apple-darwin.tar.gz|" "$FORMULA"
perl -i -pe "s|releases/download/v[^/]+/hearth-v[^-]+(-[^-]+)?-x86_64-apple-darwin\.tar\.gz|releases/download/$TAG/hearth-$TAG-x86_64-apple-darwin.tar.gz|" "$FORMULA"

# Replace sha256 lines positionally: first one belongs to arm branch, second to x86 branch.
python3 - "$FORMULA" "$ARM_SHA" "$X86_SHA" <<'PY'
import re, sys, pathlib
path, arm, x86 = sys.argv[1], sys.argv[2], sys.argv[3]
p = pathlib.Path(path)
text = p.read_text()
shas = [arm, x86]
def repl(match):
    return f'sha256 "{shas.pop(0)}"' if shas else match.group(0)
new = re.sub(r'sha256\s+"[0-9a-fA-F]{64}"', repl, text, count=2)
p.write_text(new)
PY

echo "==> Diff preview"
git --no-pager diff -- "$FORMULA"

echo "==> Creating branch ${BRANCH}"
git checkout -B "$BRANCH"
git add "$FORMULA"
git commit -m "hearth: bump to ${TAG}"

echo "==> Pushing branch"
git push -u origin "$BRANCH"

echo "==> Opening PR"
gh pr create \
  -R "$TAP_REPO" \
  -B main \
  -H "$BRANCH" \
  --title "hearth: bump to ${TAG}" \
  --body "Automated bump to [\`${TAG}\`](https://github.com/${SOURCE_REPO}/releases/tag/${TAG}).

- arm64 sha256: \`${ARM_SHA}\`
- x86_64 sha256: \`${X86_SHA}\`

Generated by .agents/tap-bump/bump-to-tag.sh in Naoray/hearth.
Do NOT auto-merge — maintainer approves."

echo "==> Done. PR opened on ${TAP_REPO}. Maintainer must approve + merge."
