//! Wrapper-script harness for engines that need a one-shot init step before
//! the long-running binary takes over.
//!
//! Per orchestrator brief (P0 #1, #3): init runs from a shell wrapper script
//! that
//!   1. acquires `flock -x` on `<data_dir>/.init.lock`
//!   2. refuses to start if the datadir is half-initialized (non-empty without
//!      the `.hearth-init-complete` sentinel)
//!   3. runs the init command exactly once, writes the sentinel only on
//!      exit-code 0
//!   4. `exec`s the engine binary so the PID is the engine's, not the wrapper's
//!
//! `ManagedService::command` points at the wrapper script, args is empty —
//! group_spawn() inherits the post-exec PID.

use std::path::{Path, PathBuf};

/// Spec for an engine that needs a one-shot init step.
pub struct WrapperSpec<'a> {
    /// Short engine name (used in script filename + log lines). E.g. "postgres".
    pub engine: &'a str,
    /// Absolute path to the engine binary that should run after init.
    pub engine_binary: &'a Path,
    /// Args passed to the engine binary post-init.
    pub engine_args: &'a [String],
    /// Absolute path to the engine's data directory.
    pub data_dir: &'a Path,
    /// Absolute path to the engine's run directory (sockets, pidfiles).
    pub run_dir: &'a Path,
    /// Shell command (one line, properly quoted) that performs init.
    /// Run only if `<data_dir>/.hearth-init-complete` is absent.
    pub init_command: String,
    /// Optional permission octal for `data_dir` and `run_dir`. Postgres needs
    /// 0o700 on its socket dir. Leave None to keep the umask default.
    pub dir_mode: Option<u32>,
}

/// Write the wrapper script to `<run_dir>/init-<engine>.sh` and make it
/// executable. Returns the script path so the caller can stash it in
/// `ManagedService::command`.
pub fn write_wrapper_script(spec: &WrapperSpec<'_>) -> anyhow::Result<PathBuf> {
    std::fs::create_dir_all(spec.run_dir)?;
    std::fs::create_dir_all(spec.data_dir)?;

    let script_path = spec.run_dir.join(format!("init-{}.sh", spec.engine));
    let exec_line = build_exec_line(spec.engine_binary, spec.engine_args);
    let dir_mode_line = match spec.dir_mode {
        Some(mode) => format!("chmod {:o} {} {}", mode, shell_quote(spec.data_dir), shell_quote(spec.run_dir)),
        None => String::new(),
    };

    let script = format!(
        r#"#!/usr/bin/env bash
# Generated by hearth-daemon — do not edit by hand.
# Engine: {engine}
set -euo pipefail

DATA_DIR={data}
RUN_DIR={run}
SENTINEL="$DATA_DIR/.hearth-init-complete"
LOCK_DIR="$DATA_DIR/.init.lockd"

mkdir -p "$DATA_DIR" "$RUN_DIR"
{dir_mode}

# mkdir-based lock: portable on macOS (no flock(1)), atomic per POSIX. Holds
# while init runs so two concurrent start attempts can't both initdb.
acquired=0
for _ in $(seq 1 600); do
    if mkdir "$LOCK_DIR" 2>/dev/null; then
        acquired=1
        break
    fi
    sleep 0.1
done
if [ $acquired -ne 1 ]; then
    echo "ERROR: could not acquire {engine} init lock at $LOCK_DIR after 60s" >&2
    exit 12
fi
trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT

if [ ! -f "$SENTINEL" ]; then
    # Half-init detection: datadir contains files other than the lock itself
    # but the completion sentinel is missing. Refuse to proceed — manual
    # recovery required.
    half_init=$(find "$DATA_DIR" -mindepth 1 -maxdepth 1 \
        ! -name '.init.lockd' \
        ! -name '.hearth-init-complete' \
        -print -quit 2>/dev/null || true)
    if [ -n "$half_init" ]; then
        echo "ERROR: {engine} datadir half-initialized at $DATA_DIR" >&2
        echo "       rm -rf $DATA_DIR and retry" >&2
        exit 11
    fi

    echo "[hearth] initializing {engine} datadir at $DATA_DIR" >&2
    {init_command}
    touch "$SENTINEL"
    echo "[hearth] {engine} init complete" >&2
fi

# Release lock BEFORE exec — the engine inherits the script's traps otherwise.
rmdir "$LOCK_DIR" 2>/dev/null || true
trap - EXIT

exec {exec_line}
"#,
        engine = spec.engine,
        data = shell_quote(spec.data_dir),
        run = shell_quote(spec.run_dir),
        dir_mode = dir_mode_line,
        init_command = spec.init_command,
        exec_line = exec_line,
    );

    std::fs::write(&script_path, script)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&script_path)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&script_path, perms)?;
    }

    Ok(script_path)
}

fn build_exec_line(binary: &Path, args: &[String]) -> String {
    let mut parts = Vec::with_capacity(args.len() + 1);
    parts.push(shell_quote(binary));
    for a in args {
        parts.push(shell_quote_str(a));
    }
    parts.join(" ")
}

fn shell_quote(path: &Path) -> String {
    shell_quote_str(&path.to_string_lossy())
}

/// POSIX single-quoted string escape. `'` is replaced with `'\''`.
fn shell_quote_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_executable_wrapper_script() {
        let tmp = tempfile::TempDir::new().unwrap();
        let run = tmp.path().join("run");
        let data = tmp.path().join("data/postgres");
        let bin = PathBuf::from("/opt/homebrew/opt/postgresql@17/bin/postgres");

        let path = write_wrapper_script(&WrapperSpec {
            engine: "postgres",
            engine_binary: &bin,
            engine_args: &["-D".to_string(), data.to_string_lossy().to_string()],
            data_dir: &data,
            run_dir: &run,
            init_command: "true".to_string(),
            dir_mode: Some(0o700),
        })
        .unwrap();

        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("mkdir \"$LOCK_DIR\""));
        assert!(content.contains(".hearth-init-complete"));
        assert!(content.contains("postgresql@17/bin/postgres"));
        assert!(content.contains("half-initialized"));
        assert!(content.contains("chmod 700"));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o755);
        }
    }

    #[test]
    fn shell_quote_escapes_single_quotes() {
        assert_eq!(shell_quote_str("foo"), "'foo'");
        assert_eq!(shell_quote_str("it's"), "'it'\\''s'");
        assert_eq!(shell_quote_str(""), "''");
    }

    #[test]
    fn wrapper_runs_init_then_execs_command() {
        // End-to-end: write a wrapper whose init touches a marker and whose
        // "engine binary" is `true`. Run it. Marker should exist; second run
        // must NOT re-touch (sentinel skips init).
        let tmp = tempfile::TempDir::new().unwrap();
        let run = tmp.path().join("run");
        let data = tmp.path().join("data");
        let marker = tmp.path().join("init-marker");

        // Init writes the marker. The first run will create it; second run
        // (with sentinel present) must NOT.
        let init_cmd = format!("touch {}", shell_quote(&marker));
        let path = write_wrapper_script(&WrapperSpec {
            engine: "fake",
            engine_binary: Path::new("/usr/bin/true"),
            engine_args: &[],
            data_dir: &data,
            run_dir: &run,
            init_command: init_cmd,
            dir_mode: None,
        })
        .unwrap();

        // First run
        let status = std::process::Command::new(&path).status().unwrap();
        assert!(status.success(), "wrapper first run should succeed");
        assert!(marker.exists(), "init should have created marker");
        assert!(
            data.join(".hearth-init-complete").exists(),
            "sentinel must be present"
        );

        // Delete the marker, run again — sentinel should skip init.
        std::fs::remove_file(&marker).unwrap();
        let status2 = std::process::Command::new(&path).status().unwrap();
        assert!(status2.success(), "wrapper second run should succeed");
        assert!(
            !marker.exists(),
            "init must NOT re-run when sentinel is present"
        );
    }

    #[test]
    fn wrapper_refuses_half_initialized_datadir() {
        let tmp = tempfile::TempDir::new().unwrap();
        let run = tmp.path().join("run");
        let data = tmp.path().join("data");
        std::fs::create_dir_all(&data).unwrap();
        // Simulate half-init: write a file but DO NOT write the sentinel.
        std::fs::write(data.join("stray-file"), "leftover from crashed init").unwrap();

        let path = write_wrapper_script(&WrapperSpec {
            engine: "fake",
            engine_binary: Path::new("/usr/bin/true"),
            engine_args: &[],
            data_dir: &data,
            run_dir: &run,
            init_command: "true".to_string(),
            dir_mode: None,
        })
        .unwrap();

        let output = std::process::Command::new(&path).output().unwrap();
        assert!(!output.status.success(), "wrapper must refuse half-init");
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("half-initialized"),
            "stderr must explain half-init, got: {stderr}"
        );
    }
}
